### PR TITLE
Update expected TUR condition

### PR DESCRIPTION
**Pull request by rajivnathan**
Related PR: https://github.com/codeready-toolchain/host-operator/pull/559

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
Is this PR needed at all? :-)

**Comment by rajivnathan** [comment]
@MatousJobanek yes, because there's a minor difference in the expected reason. It changed from using `toolchainv1alpha1.TemplateUpdateRequestUnableToUpdateReason` to `toolchainv1alpha1.TemplateUpdateRequestUpdatingReason`. Without it the test fails 🙂

**Comment by MatousJobanek** [comment]
ah, ok - I'm bad at noticing such tiny differences :smile: :man_facepalming: 
Thanks for clarifying :+1:

**Comment by rajivnathan** [comment]
I wouldn't have noticed it either because I moved the whole block of code 😄

**Pull request merged**
