### PR TITLE
SANDBOX-555: remove unnecessary assertions

### PR DESCRIPTION
**Pull request by rsoaresd**
# Description
The current PR removes unnecessary assertions.

## Issue ticket number and link
[SANDBOX-555](https://issues.redhat.com/browse/SANDBOX-555)

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
Nice catch! 👏 

Thanks for cleaning this up!

**Review by MatousJobanek — APPROVED** [review]

**Review by ranakan19 — APPROVED** [review]
LGTM

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
