### PR TITLE
Add test for gitopsdeployments to appstudio-user-actions role

### PR DESCRIPTION
**Pull request by jgwest**
This PR:
- Adds a test for the gitopsdeployment resource of the appstudio-user-action

See https://github.com/codeready-toolchain/host-operator/pull/605

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]

**Comment by MatousJobanek** [comment]
@jgwest you need to update also the expected number of Rules defined in the Role: https://github.com/codeready-toolchain/toolchain-e2e/blob/284718ce18296b75fe0026ef0b307d7c8bf510ec/testsupport/tiers/checks.go#L969

**Review by alexeykazakov — APPROVED** [review]
I also added a check for the ns label: https://github.com/codeready-toolchain/toolchain-e2e/pull/494/commits/e3e19ae512f7093fae073cfaea298b2ab17deb31

**Pull request merged**
