### PR TITLE
Add simple test for forbidden username transformation

### PR DESCRIPTION
**Pull request by sbryzak**
Fixes https://issues.redhat.com/browse/CRT-783

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
very simple :star_struck:

**Review by alexeykazakov — COMMENTED** [review]
Please add a test for a kubernetes- username too.

**Comment by MatousJobanek** [comment]
@sbryzak it looks like you have branches in two different repos with the same name `CRT-783` - the test setup logic doesn't know which branch it should pair with. See the error:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/202/pull-ci-codeready-toolchain-toolchain-e2e-master-images/1333969284006678528#1:build-log.txt%3A323

**Comment by sbryzak** [comment]
I've been digging into this all day and I had the same suspicion so I've just deleted my registration-service branch.  Why does the build process even consider this branch if there is no active pull request for it?

**Pull request merged**
