### PR TITLE
Update services quota to 30

### PR DESCRIPTION
**Pull request by rajivnathan**
Related PR: https://github.com/codeready-toolchain/host-operator/pull/574

### CODE REVIEW

**Comment by rajivnathan** [comment]
e2e test failed with the following error:
```
=== CONT  TestRetargetSpace/to_no_other_cluster
    space_test.go:179: 
        	Error Trace:	space_test.go:179
        	Error:      	Received unexpected error:
        	            	Operation cannot be fulfilled on spaces.toolchain.dev.openshift.com "oddity-cf2b9558-c242-4a8f-8317-b2df8e31f65b": the object has been modified; please apply your changes to the latest version and try again
        	Test:       	TestRetargetSpace/to_no_other_cluster
```

Will handle it in a separate PR

**Review by alexeykazakov — APPROVED** [review]

**Review by xcoulon — APPROVED** [review]

**Comment by MatousJobanek** [comment]
> Will handle it in a separate PR

thanks - we should update it in the same way as we do with UserSignup: https://github.com/codeready-toolchain/toolchain-e2e/blob/master/testsupport/wait/host.go#L227-L244

**Pull request merged**
