### PR TITLE
User tier test

### PR DESCRIPTION
**Pull request by rajivnathan**
Related PR: https://github.com/codeready-toolchain/host-operator/pull/632

Summary of changes:
- Test user tier update mechanism
- Verify all user tiers are created with correct values

Initial review was on https://github.com/codeready-toolchain/toolchain-e2e/pull/545

### CODE REVIEW

**Comment by rajivnathan** [comment]
/retest
infra issue

**Review by MatousJobanek — APPROVED** [review]

**Comment by rajivnathan** [comment]
/retest
flaky proxy test

**Pull request merged**
