### PR TITLE
Test for codeready-toolchain/host-operator#610

### PR DESCRIPTION
**Pull request by Michkov**
codeready-toolchain/host-operator#610

### CODE REVIEW

**Comment by MatousJobanek** [comment]
You also need to update the expected number of Rules: https://github.com/codeready-toolchain/toolchain-e2e/blob/f5a1213772df896511a596bd014bcd5b62eca434/testsupport/tiers/checks.go#L983

**Comment by alexeykazakov** [comment]
> You also need to update the expected number of Rules:

Updated: https://github.com/codeready-toolchain/toolchain-e2e/pull/500/commits/d0938c19359823abb73527b0ee1319d5fc313a95

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
openshift-ci issue this time... trying again
/retest

**Pull request merged**
