### PR TITLE
add viewer role for appstudio

### PR DESCRIPTION
**Pull request by filariow**
linked to https://github.com/codeready-toolchain/host-operator/pull/1011

JIRA: https://issues.redhat.com/browse/ASC-490

Signed-off-by: Francesco Ilario <filario@redhat.com>

### CODE REVIEW

**Review by dperaza4dustbit — APPROVED** [review]
looks OK

**Review by sadlerap — APPROVED** [review]

**Comment by filariow** [comment]
@rsoaresd thanks for looking into it! done in 8258114e7976db744132dd0f6326f8bac9416fa9

**Review by MatousJobanek — APPROVED** [review]
Looks good :+1:

**Review by mfrancisc — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
