### PR TITLE
Update to Google uuid as changed in toolchaincommon

### PR DESCRIPTION
**Pull request by fbm3307**
This is updating the UUID pkg from `gofrs` to `Google`

Since in Toolchain - Common [PR](https://github.com/codeready-toolchain/toolchain-common/pull/395 ) it is already updated , Updating them in its related repos 

- Registration Service - https://github.com/codeready-toolchain/registration-service/pull/429

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
Nice 👍

**Review by MatousJobanek — APPROVED** [review]
/lgtm

**Comment by MatousJobanek** [comment]
Looks like some flakiness https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/968/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1788514031074545664/build-log.txt
Could you please take a look at it?

**Review by alexeykazakov — APPROVED** [review]

**Review by ranakan19 — APPROVED** [review]

**Review by metlos — APPROVED** [review]
Got bitten by this, too. Great you're tackling it already :)

**Pull request merged**
