### PR TITLE
KUBESAW-172: Restart host-operator at the end of the register-member command

### PR DESCRIPTION
**Pull request by fbm3307**
Removing the restarting of host operator (deleting pods) from `set-up toolchain clusters` make command, as we are  going to use the `Restart` command from `Register-Member`  command and restart host operator

KSCTL PR : https://github.com/kubesaw/ksctl/pull/90

### CODE REVIEW

**Comment by fbm3307** [comment]
have changed the related PR in ksctl to fix the e2e error, hence restarting the e2e test

**Comment by fbm3307** [comment]
/test e2e

as it was a flaky test 
`context deadline exceeded when waiting for usersignup to be deactivated`

**Review by mfrancisc — APPROVED** [review]
👍

**Review by MatousJobanek — APPROVED** [review]

**Comment by fbm3307** [comment]
/test e2e

restarting the e2e as changes pushed to paired PR

**Pull request merged**
