### PR TITLE
feat: check for Konflux new Project* CRs

### PR DESCRIPTION
**Pull request by ifireball**
Tests for codeready-toolchain/host-operator#1004

### CODE REVIEW

**Comment by mfrancisc** [comment]
FYI @filariow @sadlerap @hugares @gbenhaim @dperaza4dustbit

**Comment by ifireball** [comment]
@mfrancisc si the test failing because https://github.com/codeready-toolchain/host-operator/pull/1004 is not merged yet?

**Comment by mfrancisc** [comment]
> si the test failing because https://github.com/codeready-toolchain/host-operator/pull/1004 is not merged yet?

No , the PRs with same branch name in host and toolchain-e2e are paired and tested together , we need both to be approved and have passing tests in order to be merged at the same time. 


Looking at the error message in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/938/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1773262855982813184/build-log.txt:
```
 checks.go:1531: 
        	Error Trace:	/go/src/github.com/codeready-toolchain/toolchain-e2e/testsupport/tiers/checks.go:1531
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/testsupport/tiers/nstemplateset.go:59
        	            				/usr/local/go/src/runtime/asm_amd64.s:1598
        	Error:      	"[{[get list watch create update patch delete deletecollection] [appstudio.redhat.com] [applications components componentdetectionqueries] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [promotionruns snapshotenvironmentbindings snapshots environments] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [deploymenttargets deploymenttargetclaims] [] []} {[get list watch] [managed-gitops.redhat.com] [gitopsdeployments gitopsdeploymentmanagedenvironments gitopsdeploymentrepositorycredentials gitopsdeploymentsyncruns] [] []} {[get list watch create update patch delete] [tekton.dev] [pipelineruns] [] []} {[get list] [results.tekton.dev] [results records logs] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [enterprisecontractpolicies integrationtestscenarios releases releasestrategies releaseplans releaseplanadmissions] [] []} {[get list watch create update patch delete] [jvmbuildservice.io] [jbsconfigs artifactbuilds] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [spiaccesstokenbindings spiaccesschecks spiaccesstokens spifilecontentrequests spiaccesstokendataupdates] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [remotesecrets] [] []} {[get list watch create update patch delete] [] [secrets] [] []} {[get list watch create update patch delete] [] [configmaps] [] []} {[get list watch create update patch delete] [appstudio.redhat.com] [buildpipelineselectors] [] []} {[get list watch update patch] [] [serviceaccounts] [appstudio-pipeline] []} {[create] [] [pods/exec] [] []} {[get list watch create update patch delete] [toolchain.dev.openshift.com] [spacebindingrequests] [] []} {[get list watch create update patch delete] [projctl.konflux.dev] [projects projectdevelopmentstreams projectdevelopmentstreamtemplates] [] []}]" should have 16 item(s), but has 17
```

you need to bump by 1 the expected number of rules also the number of Rules for admin in https://github.com/codeready-toolchain/toolchain-e2e/blob/7b76124d7c9010ae66f8d288a8695dbb5bf1df4b/testsupport/tiers/checks.go#L1531 

for maintainer https://github.com/codeready-toolchain/toolchain-e2e/blob/7b76124d7c9010ae66f8d288a8695dbb5bf1df4b/testsupport/tiers/checks.go#L1626

and  for contributor https://github.com/codeready-toolchain/toolchain-e2e/blob/7b76124d7c9010ae66f8d288a8695dbb5bf1df4b/testsupport/tiers/checks.go#L1715

**Comment by ifireball** [comment]
> 
> you need to bump by 1 the expected number of Rules for admin in
> 
Done. But I wonder if it would make sense to change all those lines to be:
```
assert.Len(t, role.Rules, len(expected.Rules))
```
Or wither it makes sense to have the length check there at all given that we do an equality check between the slices anyway.

**Comment by ifireball** [comment]
@mfrancisc can you approve please?

**Comment by rsoaresd** [comment]
Hello, @ifireball!


[The latest run](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_host-operator/1004/pull-ci-codeready-toolchain-host-operator-master-e2e/1773262513035546624#1:build-log.txt%3A3613-3618) failed in TestAfterMigration/run_migration_setup_with_new_operator_versions_for_compatibility with:

```
should have 16 item(s), but has 17 
```

I believe the test needs to be updated to match the changes in the paired PR.

**Review by mfrancisc — APPROVED** [review]

**Comment by mfrancisc** [comment]
> But I wonder if it would make sense to change all those lines

yeah it's maybe a simplification we can do.  Thanks for bringing that up!

**Review by alexeykazakov — APPROVED** [review]

**Pull request merged**
