### PR TITLE
feat(HACBS-1969): add read rbac of DT, DTC and DeploymentTargetClass …

### PR DESCRIPTION
**Pull request by hongweiliu17**
…to nstemplatetiers

This PR add read RBAC of DT, DTC and DeploymentTargetClass to nstemplatetiers.

Corresponding host operator PR: https://github.com/codeready-toolchain/host-operator/pull/764

### CODE REVIEW

**Review by alexeykazakov — COMMENTED** [review]
Looks good but you also have to update the rule count from 13 to 14 here: https://github.com/codeready-toolchain/toolchain-e2e/pull/680/files#diff-656de6540cafb22fc3a2da30b608ceff7c22769a72bb58bf9ec90ad4fc110f75R1168

**Comment by hongweiliu17** [comment]
> Looks good but you also have to update the rule count from 13 to 14 here: https://github.com/codeready-toolchain/toolchain-e2e/pull/680/files#diff-656de6540cafb22fc3a2da30b608ceff7c22769a72bb58bf9ec90ad4fc110f75R1168

Thanks! Updated.

**Review by alexeykazakov — APPROVED** [review]

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
