### PR TITLE
PLNSRVCE-1167: add logs resource to tekton results RBAC

### PR DESCRIPTION
**Pull request by gabemontero**
paired with https://github.com/codeready-toolchain/host-operator/pull/796

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by gabemontero** [comment]
hypershift fail

/retest

**Comment by gabemontero** [comment]
another hypershift fail .... we try again later

**Comment by alexeykazakov** [comment]
Still having issues with the infra

/retest

**Comment by gabemontero** [comment]
the host-operator PR passed without infra issues ... let's see how pervasive that health is

/retest

**Comment by alexeykazakov** [comment]
The host repo doesn't use HyperShift. We enabled in the e2e repo only for now. As experiment to see how stable it is.

/retest

**Comment by alexeykazakov** [comment]
Ok. Since the paired host PR is green and my understanding is that this change is quite important and needed to be addressed rather sooner than later I'm going to merge it. We can deal with the hypershift infra issue on Monday.

**Comment by gabemontero** [comment]
On Sun, Apr 30, 2023 at 11:49 AM Alexey Kazakov ***@***.***>
wrote:

> Ok. Since the paired host PR is green and my understanding is that this
> change is quite important and needed to be addressed rather sooner than
> later I'm going to merge it. We can deal with the hypershift infra issue on
> Monday.
>
cool / thanks

In case it is not clear to others who see this, the end game around this PR
is the HAC viewing pipielinerun logs via tekton results instead of viewing
the associated pod logs of the pipelinerun

That shift in turn allows for mor aggressive pruning

**Pull request merged**
