### PR TITLE
Set CPU limit and request for Autoscaler Buffer

### PR DESCRIPTION
**Pull request by alexeykazakov**
Paired with https://github.com/codeready-toolchain/member-operator/pull/592

Requires https://github.com/codeready-toolchain/host-operator/pull/1071

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]

**Comment by MatousJobanek** [comment]
/retest
host-operator PR was merged

**Comment by MatousJobanek** [comment]
I was looking at the e2e test error - it's failing because the test is too quick with the checks and it doesn't wait until the second member deployment updates the autoscaler buffer. 
Ideally, instead of just getting the resource we should wait until it contains the expected values.

**Comment by alexeykazakov** [comment]
> Ideally, instead of just getting the resource we should wait until it contains the expected values.

Yep. Added it here: https://github.com/codeready-toolchain/toolchain-e2e/pull/1027/commits/9ebfcba20eb0e19cfc8dbf9fe331db78a6368573
It's not ideal and looks a bit ugly but should work.

**Comment by alexeykazakov** [comment]
@MatousJobanek It looks like the toolchainconfig is not applied from this PR and applied from the master branch only. Looks like a bug in our migration test setup. Will try to look at it.

**Comment by MatousJobanek** [comment]
fix https://github.com/codeready-toolchain/toolchain-e2e/pull/1028

**Comment by MatousJobanek** [comment]
/retest
failure not related to this PR. I'm investigating it https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1027/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1821788497304883200

**Comment by MatousJobanek** [comment]
>failure not related to this PR. I'm investigating it 

There was apparently some issue with the cache sync in the controller. I don't think that we can do anything about it. :shrug: In prod, it should get eventually fixed.

**Pull request merged**
