### PR TITLE
disable unkown-cluster-related test

### PR DESCRIPTION
**Pull request by MatousJobanek**
https://issues.redhat.com/browse/CRT-1775

paired PR: https://github.com/codeready-toolchain/host-operator/pull/791

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
😢 

but I agree that we should probably delete the space even if it's doesn't have a targetCluster 🤷‍♂️

**Comment by MatousJobanek** [comment]
I don't like disabling tests, but this causes so many flakiness and failures so this is the fastest way to make the e2e suite working for already existing PRs. 
And it's definitely something we should fix on the controller-side first.

**Comment by mfrancisc** [comment]
>  I don't like disabling tests ..

@MatousJobanek I agree, and I don't like it either, but at the moment is causing more disruption than actually gating critical functionality IMO.

**Review by alexeykazakov — APPROVED** [review]

**Review by rajivnathan — APPROVED** [review]

**Comment by MatousJobanek** [comment]
/retest
infra

**Comment by MatousJobanek** [comment]
/retest
[2db6ac0](https://github.com/codeready-toolchain/host-operator/pull/791/commits/2db6ac0f35c5ef0a5b8ac4fdc2334c396e85eb17)

**Pull request merged**
