### PR TITLE
add deploy-toolchain-resources-e2e

### PR DESCRIPTION
**Pull request by rsoaresd**
# Description
- add `deploy-toolchain-resources-e2e` to deploy the same resources as `make test-e2e` but doesn't run tests. It will be useful for wa

## Issue ticket number and link
[SANDBOX-811](https://issues.redhat.com/browse/SANDBOX-811)

### CODE REVIEW

**Review by rajivnathan — APPROVED** [review]
Nice 👍 Just a couple very minor suggestions

**Review by mfrancisc — COMMENTED** [review]
Looks good 👍 

Alternatively you could have something like this:

```
.PHONY: deploy-single-member-e2e
## Deploy operators in e2e mode with single member without running tests
deploy-single-member-e2e: SECOND_MEMBER_MODE=false
deploy-single-member-e2e: HOST_NS=toolchain-host-operator
deploy-single-member-e2e: MEMBER_NS=toolchain-member-operator
deploy-single-member-e2e: REGISTRATION_SERVICE_NS=toolchain-host-operator
deploy-single-member-e2e: prepare-e2e deploy-e2e
        @echo "The e2e deployment successfully finished"
	@echo "To clean the cluster run 'make clean-e2e-resources'"
```

**Comment by rsoaresd** [comment]
> Looks good 👍
> 
> Alternatively you could have something like this:
> 
> ```
> .PHONY: deploy-single-member-e2e
> ## Deploy operators in e2e mode with single member without running tests
> deploy-single-member-e2e: SECOND_MEMBER_MODE=false
> deploy-single-member-e2e: HOST_NS=toolchain-host-operator
> deploy-single-member-e2e: MEMBER_NS=toolchain-member-operator
> deploy-single-member-e2e: REGISTRATION_SERVICE_NS=toolchain-host-operator
> deploy-single-member-e2e: prepare-e2e deploy-e2e
>         @echo "The e2e deployment successfully finished"
> 	@echo "To clean the cluster run 'make clean-e2e-resources'"
> ```

Thanks, @mfrancisc! Addressed it! I did not include the echo commands because `deploy-e2e` already [prints](https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L94) that the deployment finished successfully. Regarding the clean-up, I changed to use `prepare-and-deploy-e2e` which [prints](https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L61) it.

If we set the vars in the suggested way, it will fail because [ifeq](https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L373) is not dynamic and does not re-evaluate variables updated during execution, so even if we changed `SECOND_MEMBER_MODE` to false, it was being evaluated as true and it was deploying the second member.

**Comment by mfrancisc** [comment]
> If we set the vars in the suggested way, it will fail because [ifeq](https://github.com/codeready-toolchain/toolchain-e2e/blob/master/make/test.mk#L373) is not dynamic and does not re-evaluate variables updated during execution, so even if we changed SECOND_MEMBER_MODE to false, it was being evaluated as true and it was deploying the second member.

Thanks for looking into it @rsoaresd , you're right about the `ifeq` , I would need to change that to bash if syntax. But that was just a suggestion, your approach works fine 👍

**Review by mfrancisc — APPROVED** [review]
Great job 👍 

Thanks for answering my comments/questions.

**Pull request merged**
