### PR TITLE
chore: use digest instead of tags

### PR DESCRIPTION
**Pull request by MatousJobanek**
To properly verify that the changes introduced here https://github.com/codeready-toolchain/api/commit/d37dc262950f4345055d85c3d7e2aa8ba88c819a are working properly (in other words, that CSV and OLM can use digests instead of tags) use digests instead of tags in e2e tests too

### CODE REVIEW

**Comment by alexeykazakov** [comment]
> docker pull registry.svc.ci.openshift.org/ci-op-4m5xk0zy/stable:registration-service
/bin/bash: docker: command not found

**Comment by MatousJobanek** [comment]
> docker pull registry.svc.ci.openshift.org/ci-op-4m5xk0zy/stable:registration-service
/bin/bash: docker: command not found

I know, I had to switch to API call: 818dadb 
I will do it also in the scripts ;-)

**Comment by MatousJobanek** [comment]
and yeah, it's doing only for `quay.io`, which means that it's using it only for local testing, unfortunately, there is no other easy way. 
I can try to improve it later, but for now the local verification should be enough

**Pull request merged**
