### PR TITLE
fix ksctl pairing

### PR DESCRIPTION
**Pull request by MatousJobanek**
* pairing is not executed if `DEPLOY_LATEST` is set to `true` - this means, in appstudio makefile targets
* added more logs so it's clear what version is gonna be used
* extracted git cloning and merging to a separate target - the reason is that the if statements are evaluated at the beginning of the target, so setting it in the middle of it doesn't have any effect on the result of the if statement. Thus, there were problems with the `ifneq ($(strip $(REMOTE_KSCTL_BRANCH)),)`

TBH, the special behavior of makefile targets drives me crazy and I'm thinking about moving it to a bash script.
I'll take a look at the options and think about the best approach.

### CODE REVIEW

**Review by sadlerap — APPROVED** [review]
I'm fine with this in a makefile, but I agree with your sentiment - this should maybe get moved to a script at some point.

**Review by alexeykazakov — APPROVED** [review]

**Review by mfrancisc — APPROVED** [review]
Thanks for fixing it 👍 

I've tried it locally ( forcing the CI variables ) and is working!

**Comment by mfrancisc** [comment]
> TBH, the special behavior of makefile targets drives me crazy and I'm thinking about moving it to a bash script.
I'll take a look at the options and think about the best approach.

Agree , moving it to bash would be better indeed . I wasn't aware of this special behavior of the `if` statement. Thanks for letting us know.

**Comment by sadlerap** [comment]
It's been pointed out to me that `DEPLOY_LATEST` doesn't work for us on workspaces, since we build our own version of kubesaw for testing purposes that may or may not be based off of the latest commit that's landed.

Would it be possible to have some kind of way of disabling PR pairing without requiring the deployment of the latest version of kubesaw?  Maybe have a parameter like `CI_DISABLE_PAIRING` or something similar?

**Comment by MatousJobanek** [comment]
Interesting, I wasn't aware of that. 
In infra-deployments, in the PR that you made https://github.com/redhat-appstudio/infra-deployments/pull/4324, you updated logic that is running the `appstudio-dev-deploy-latest` target. This target automatically sets the `DEPLOY_LATEST` variable to `true` and I cannot find any other place that would do something else :man_shrugging: 

A few people reach out to us that the infra-deployments logic is failing for them because of missing ksctl binary. The reason was your logic that installs the latest ksctl to the default GOBIN directory, which they didn't have added to their PATH. That's why I proposed this change so you can remove the line that installs ksctl to the default GOBIN directory, and toolchain-e2e can use the local temporal location for the binary, and thus infra-deployments setup doesn't cause any other issues when executed locally.

**Comment by MatousJobanek** [comment]
anyway, let me create another PR that should avoid running the pairing logic in other environments

**Comment by MatousJobanek** [comment]
@sadlerap see https://github.com/codeready-toolchain/toolchain-e2e/pull/1041

**Pull request merged**
