### PR TITLE
SANDBOX-555: remove unnecessary empty lines

### PR DESCRIPTION
**Pull request by rsoaresd**
# Description
The current PR removes unnecessary empty lines.

## Issue ticket number and link
[SANDBOX-555](https://issues.redhat.com/browse/SANDBOX-555)

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
I'm curious if there any reason for that besides just personal format preference?

**Comment by rsoaresd** [comment]
> I'm curious if there any reason for that besides just personal format preference?

@alexeykazakov, just to "follow" the pattern of the majority of the code (no empty line after func definition, for example)

**Comment by rsoaresd** [comment]
/retest


error:
```
  * could not run steps: step [release-inputs:initial] failed: failed to import tags on imagestream ci-op-4zs3phjr/stable-initial: unable to import tag ci-op-4zs3phjr/stable-initial@kubefed-controller: Timeout: request did not complete within requested timeout - context deadline exceeded even with retries 
INFO[2024-03-14T14:47:42Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:creating_release_images' 
```

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
