### PR TITLE
Add rules for SecretStore and ExternalSecret CRs 

### PR DESCRIPTION
**Pull request by avinashsingh77**
This change adds a Role and RoleBinding to the tenant use to CRUD on SecretStore and ExternalSecret CRs provided by external-secrets.io

This is meant for testing if this can enable tenants to create SecretStore and ExternalSecret from their own self-hosted or managed secrets backend

Paired PR in `codeready-toolchain/host-operator` - https://github.com/codeready-toolchain/host-operator/pull/1034

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Please do not forget to add the links to the paired PRs description (so the operator PR has a link to the paired e2e test PR and the e2e one has a link to the paired operator PR). It really helps with PR review.

**Review by alexeykazakov — APPROVED** [review]

**Comment by gbenhaim** [comment]
lgtm

**Pull request merged**
