### PR TITLE
add limit ranges on namespace templates

### PR DESCRIPTION
**Pull request by xcoulon**
updated the "provider" label

updates https://issues.redhat.com/browse/CRT-460

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
> codeready-toolchain/host-operator#160

ok, thanks for the pointer! Let me add a check on the number of LimitRanges in each namespace, then ;)

**Comment by xcoulon** [comment]
> > [codeready-toolchain/host-operator#160](https://github.com/codeready-toolchain/host-operator/pull/160)
> 
> ok, thanks for the pointer! Let me add a check on the number of LimitRanges in each namespace, then ;)

@MatousJobanek done in aca4599

**Comment by MatousJobanek** [comment]
cool :+1: 
could you please add it also to the team tier checks? https://github.com/codeready-toolchain/toolchain-e2e/blob/master/tiers/checks.go#L92

**Comment by xcoulon** [comment]
> cool 👍
> could you please add it also to the team tier checks? https://github.com/codeready-toolchain/toolchain-e2e/blob/master/tiers/checks.go#L92

done in 9e330f4

**Pull request merged**
