### PR TITLE
disable phone verification in dev & appstudio environments

### PR DESCRIPTION
**Pull request by MatousJobanek**
based on latest discussions:
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1693460828997409
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1693337601323839?thread_ts=1693316915.769479&cid=CHK0J6HT6

let's disable the phone verification step in dev environment - you know, to simplify it for other developers.

While doing so, I also noticed that the phone verification was enabled also in appstudio-e2e environment, which doesn't make any sense at all. So I disabled it there as well cc @jkopriva @sawood14012

### CODE REVIEW

**Review by jkopriva — APPROVED** [review]
Thank you for this change!

**Review by mfrancisc — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]
+1. Was thinking about that too. Not sure why we enabled it in the first place.

**Comment by MatousJobanek** [comment]
/retest
there was a timeout on the api call - most likely infra glitch:
```
Get "https://api.ci-op-755199vn-ceea8.origin-ci-int-aws.dev.rhcloud.com:6443/apis/user.openshift.io/v1/users/mig-appst?timeout=6s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by MatousJobanek** [comment]
/retest
infra

**Pull request merged**
