### PR TITLE
Remove deprecated TargetCluster from MUR status

### PR DESCRIPTION
**Pull request by alexeykazakov**
This PR is purely to verify that the changes in API and common do not break the member operator:
https://github.com/codeready-toolchain/api/pull/66
https://github.com/codeready-toolchain/toolchain-common/pull/65

When the PR from above are merged I will remove the replace and update the api and common dependencies properly.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
> so shouldn't you make PRs to this repo and to the host repo from a branch with the same name, but a different one than to the other repositories? To ensure that the e2e tests are paired only with the PR in host repo... If I understand it correctly, you wanted to verify that the changes in api and common repos that are transitively available in the host repo PR will not break the other repositories (reg-service and member), correct? In that case, we should pair only with the PR in the host repo, shouldn't we?

Changes in the member and reg-service PRs are just about making sure that the code still compiles tbh and that I didn't miss anything :) There is no any code changes in these repos. So, I thought it was OK if the e2e test are paired with all the PRs from all repos.

**Comment by MatousJobanek** [comment]
> Changes in the member and reg-service PRs are just about making sure that the code still compiles tbh and that I didn't miss anything :) There is no any code changes in these repos. So, I thought it was OK if the e2e test are paired with all the PRs from all repos.

Ah, right. It just updates the dependencies which means that it's almost the same as the master is. Yeah, that's fine ;-)

**Pull request merged**
