### PR TITLE
refactor: drop SignupRequest interface

### PR DESCRIPTION
**Pull request by xcoulon**
just use plain implementation

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]

**Review by sbryzak — APPROVED** [review]
Looks good, but would be nice to move the interface function comments to the implementation

**Comment by xcoulon** [comment]
> Looks good, but would be nice to move the interface function comments to the implementation

oh yes, indeed! 
done in aa05592

**Comment by alexeykazakov** [comment]
> oh yes, indeed!
done in https://github.com/codeready-toolchain/toolchain-e2e/commit/aa05592758901e7d67457af1fabc88f42c6e137e

Wrong link?

**Comment by xcoulon** [comment]
> > oh yes, indeed!
> > done in [aa05592](https://github.com/codeready-toolchain/toolchain-e2e/commit/aa05592758901e7d67457af1fabc88f42c6e137e)
> 
> Wrong link?

oh, my apologies! I can't explain what happened here, so I opened another PR to restore those comments: https://github.com/codeready-toolchain/toolchain-e2e/pull/557

**Pull request merged**
