### PR TITLE
Appstudio: add access to buildpipelineselectors

### PR DESCRIPTION
**Pull request by Michkov**
BuildPipelineSelector allows modify selection of pipelineRun for build.

https://github.com/codeready-toolchain/host-operator/pull/828

### CODE REVIEW

**Review by MatousJobanek — COMMENTED** [review]
You need to update also the expected number of rules defined in each Role:

admin https://github.com/codeready-toolchain/toolchain-e2e/blob/3f772f13120c90e9bc4e4c2c89c877cc992dde13/testsupport/tiers/checks.go#L1466
maintainer https://github.com/codeready-toolchain/toolchain-e2e/blob/3f772f13120c90e9bc4e4c2c89c877cc992dde13/testsupport/tiers/checks.go#L1551
contributor https://github.com/codeready-toolchain/toolchain-e2e/blob/3f772f13120c90e9bc4e4c2c89c877cc992dde13/testsupport/tiers/checks.go#L1640

**Review by alexeykazakov — APPROVED** [review]

**Comment by alexeykazakov** [comment]
Looks good but please do not use force-push. Just keep pushing new commits when needed. It makes follow-up reviews easier.

**Review by MatousJobanek — APPROVED** [review]

**Pull request merged**
