### PR TITLE
Allow tests to still pass when phone verification enabled

### PR DESCRIPTION
**Pull request by sbryzak**
This PR accompanies https://github.com/codeready-toolchain/host-operator/pull/293 and contains fixes to the e2e tests to allow them to continue to pass when phone verification is enabled.

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
Code wise looks good.
But can we do something with making clear that these email domains are used to get the verification skipped?
Either by adding comments in the tests or (and?) by using more descriptive domain names: https://github.com/codeready-toolchain/host-operator/pull/293#pullrequestreview-499543523

**Comment by MatousJobanek** [comment]
@sbryzak didn't you miss @alexeykazakov's comments?
https://github.com/codeready-toolchain/toolchain-e2e/pull/171#pullrequestreview-499546090
https://github.com/codeready-toolchain/host-operator/pull/293#discussion_r497593514

**Pull request merged**
