### PR TITLE
Add a dedicated service account to run Tekton pipelines

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by alexeykazakov — CHANGES_REQUESTED** [review]
The PR looks good. I'm blocking it just to make sure the PR doesn't get merged until we update the member operator permissions.

**Review by MatousJobanek — APPROVED** [review]

**Comment by MatousJobanek** [comment]
@alexeykazakov what I did in this PR:
* 457cfa1
    * dropped the dummy ClusterRole 
* 9bc1751
    * fixed the expected number of RoleBindings in the `-tenant` namespace 
* afac866 
    * fixed the name of the expected ClusterRole in ClusterRoleBinding to `appstudio-pipelines-runner`
    * added check for the existence of the `appstudio-pipelines-runner` ClusterRole
    * and added codes to our cleanup Makefile target to delete the ClusterRole(Binding) resources created by OLM

**Review by alexeykazakov — APPROVED** [review]

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
