### PR TITLE
Support regexp filter for tests that needs to run

### PR DESCRIPTION
**Pull request by baijum**
This is useful to run individual tests.

Ref. https://stackoverflow.com/questions/16935965/how-to-run-test-cases-in-a-specified-file

### CODE REVIEW

**Review by mfrancisc — COMMENTED** [review]
Thanks for adding this! 

I believe by default keeps running all the tests with `-run ""` ?

Could you please add few words in the README to document this new variable and how to use it?

**Comment by baijum** [comment]
> I believe by default keeps running all the tests with `-run ""` ?

Yes. I can see 72 tests passed here. I checked this against a [recent build](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/800/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1707785323070623744) that was merged on last Friday.

> Could you please add few words in the README to document this new variable and how to use it?

Done. Please take a look: 7d93534532374caacf82c91707a5dfe78fb2f671

**Review by rajivnathan — APPROVED** [review]

**Pull request merged**
