### PR TITLE
Just testing the new ksctl register member command

### PR DESCRIPTION
**Pull request by mfrancisc**
Paired with: https://github.com/kubesaw/ksctl/pull/53

Will close once verified.

### CODE REVIEW

**Comment by mfrancisc** [comment]
/retest

migration test failed : https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1032/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1823308306198827008/build-log.txt not sure if related

**Comment by MatousJobanek** [comment]
@mfrancisc it's related - se my comment in the other PR: https://github.com/kubesaw/ksctl/pull/53#discussion_r1716583829

**Comment by mfrancisc** [comment]
> @mfrancisc it's related - se my comment in the other PR: https://github.com/kubesaw/ksctl/pull/53#discussion_r1716583829

Thanks I was looking into it locally, I've inverted the SAs apparently 🤦‍♂️

**Comment by mfrancisc** [comment]
/retest

updated the ksctl PR

**Comment by mfrancisc** [comment]
hmmm seems like it picked up master branch instead of my for now : https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1032/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1823719902742056960/artifacts/e2e/test/build-log.txt

**Comment by MatousJobanek** [comment]
yup, the pairing was broken - I didn't realize that the if statement is evaluated at the beginning of the makefile target. Here is the fix https://github.com/codeready-toolchain/toolchain-e2e/pull/1034

**Comment by MatousJobanek** [comment]
/retest
infra

**Comment by MatousJobanek** [comment]
> DEPLOY_LATEST is set to true - no pairing

:facepalm:

**Comment by mfrancisc** [comment]
I see later it installs from my branch , but it doesn't run the `register-member` command anymore:

<details>
```
detected branch registermember
# check if a branch with the same ref exists in the user's fork of ksctl repo
branches of https://github.com/mfrancisc/ksctl - checking if there is a branch registermember we could pair with.
curl https://github.com/mfrancisc/ksctl.git/info/refs?service=git-upload-pack --output -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   513    0   513    0     0  13500      0 --:--:-- --:--:-- --:--:-- 13500
001e# service=git-upload-pack
00000155a0a148a9988b4a2287dc85b744f4439c35c8e559 HEAD�multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/master filter object-format=sha1 agent=git/github-7d8f01c5c0e4
003fa0a148a9988b4a2287dc85b744f4439c35c8e559 refs/heads/master
0047635fb8cccba3b1466cdae26d3c1c4e2b91481e27 refs/heads/registermember
0000# check if the branch with the same name exists, if so then merge it with master and use the merge branch, if not then use master
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/usr/local/go/bin:/cli)
Branch ref of the user's fork to be used for pairing: "refs/heads/registermember"
# define temp dir
# delete to have clear environment
rm -rf /tmp/ksctl
git config --global user.email "devtools@redhat.com"
git config --global user.name "Devtools"
# clone
git clone --depth=1 https://github.com/kubesaw/ksctl.git /tmp/ksctl
Cloning into '/tmp/ksctl'...
# add the user's fork as remote repo
git --git-dir=/tmp/ksctl/.git --work-tree=/tmp/ksctl remote add external https://github.com/mfrancisc/ksctl.git
# fetch the branch
git --git-dir=/tmp/ksctl/.git --work-tree=/tmp/ksctl fetch external refs/heads/registermember
From https://github.com/mfrancisc/ksctl
 * branch            registermember -> FETCH_HEAD
 * [new branch]      registermember -> external/registermember
# merge the branch with master
git --git-dir=/tmp/ksctl/.git --work-tree=/tmp/ksctl merge --allow-unrelated-histories --no-commit FETCH_HEAD
Updating 0ffc21a..635fb8c
Fast-forward
 pkg/cmd/adm/register_member.go       | 390 +++++++++++++++++----------
 pkg/cmd/adm/register_member_test.go  | 508 ++++++++++++-----------------------
 pkg/cmd/generate/cli_configs.go      |   6 +-
 pkg/cmd/generate/cli_configs_test.go |   2 +-
 pkg/utils/util.go                    |  16 +-
 5 files changed, 443 insertions(+), 479 deletions(-)
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin:/usr/local/go/bin:/cli)
Installing ksctl from directory /tmp/ksctl
make -C /tmp/ksctl GOBIN=/go/src/github.com/codeready-toolchain/toolchain-e2e/build/_output/bin install
CGO_ENABLED=0 \
	go install  \
	-ldflags "-X github.com/kubesaw/ksctl/pkg/version.Commit=635fb8cccba3b1466cdae26d3c1c4e2b91481e27 -X github.com/kubesaw/ksctl/pkg/version.BuildTime=`date -u '+%Y-%m-%dT%H:%M:%SZ'`" \
         github.com/kubesaw/ksctl/cmd/ksctl/...
rm -rf /tmp/e2e-tiers-out 2>/dev/null || true
/go/src/github.com/codeready-toolchain/toolchain-e2e/build/_output/bin/ksctl generate nstemplatetiers --source deploy/nstemplatetiers --out-dir /tmp/e2e-tiers-out
```
</details>

**Comment by MatousJobanek** [comment]
The thing is that the migration suite installs the latest operators first and then it registers the member clusters. I didn't realize that the registering member clusters still happens in the context of the latest install and that the env var is still set for that command. 
let me fix it one more time and correctly

**Comment by mfrancisc** [comment]
@MatousJobanek the pairing worked fine now and the tests are passing apparently with the new command : https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1032/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1828051122380607488/artifacts/e2e/test/build-log.txt

**Comment by mfrancisc** [comment]
closing as not needed anymore, the new register-member command was merged.

**Pull request closed without merging**
