### PR TITLE
deprecate performance tests

### PR DESCRIPTION
**Pull request by mfrancisc**
Deprecate unused e2e performance tests suite

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Review by alexeykazakov — APPROVED** [review]
Is there anything to delete from the makefiles?

**Review by xcoulon — APPROVED** [review]
"Removing outdated code" would be a more appropriate title for this PR 😂

**Comment by mfrancisc** [comment]
/retest

Seems that it's now failing to restart host operator after setup migration test 🤔 

```
  init.go:52: Registration Service namespace: toolchain-host-03114724
    awaitility.go:449: waiting until deployment 'host-operator-controller-manager' in namespace 'toolchain-host-03114724' is ready
    awaitility.go:478: 
        	Error Trace:	/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/awaitility.go:478
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/init.go:67
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/once.go:68
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/once.go:59
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/init.go:44
        	            				/go/src/github.com/codeready-toolchain/toolchain-e2e/test/migration/verify/verify_migration_test.go:24
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
```

**Pull request merged**
