### PR TITLE
Chore: Add empty metrics instance for appstudio

### PR DESCRIPTION
**Pull request by sawood14012**
Hello, we are using the metrics pkg as an dependency for load testing AppStudio , well we just needed one empty metrics instance that we will add the workloads later from our script PTAL .

### CODE REVIEW

**Review by MatousJobanek — APPROVED** [review]
This looks fine, but keep in mind that the plan for the service-preview has been changed since the time we had a call regarding the load testing. Service-preview won't be based on the pre-KCP Sandbox solution but directly on the KCP.

**Comment by sawood14012** [comment]
> This looks fine, but keep in mind that the plan for the service-preview has been changed since the time we had a call regarding the load testing. Service-preview won't be based on the pre-KCP Sandbox solution but directly on the KCP.

Thanks ! will discuss and let you know the next plans

**Pull request merged**
